export const iconMap = {
    'css': '/icons/icons8-css.svg',
    'tailwind': '/icons/icons8-tailwind-css.svg',
    'material-ui': '/icons/icons8-material-ui.svg',
    'html': '/icons/icons8-html.svg',
    'javascript': '/icons/icons8-javascript.svg',
    'typescript': '/icons/icons8-typescript.svg',
    'python': '/icons/icons8-python.svg',
    'react': '/icons/icons8-react-native.svg',
    'nextjs': '/icons/icons8-nextjs.svg',
    'nodejs': '/icons/icons8-nodejs.svg',
    'npm': '/icons/icons8-npm.svg',
    'firebase': '/icons/icons8-firebase.svg',
    'mysql': '/icons/icons8-mysql.svg',
    'git': '/icons/icons8-git.svg',
    'github': '/icons/icons8-github.svg',
    'figma': '/icons/icons8-figma.svg',
    'vite': '/icons/icons8-vite.svg',
  };