export const iconMap = {
  css: "/icons/icons8-css.svg",
  tailwind: "/icons/icons8-tailwind-css.svg",
  "material-ui": "/icons/icons8-material-ui.svg",
  "framer motion": "/icons/framer-logo.svg",
  html: "/icons/icons8-html.svg",
  javascript: "/icons/icons8-javascript.svg",
  typescript: "/icons/icons8-typescript.svg",
  python: "/icons/icons8-python.svg",
  react: "/icons/icons8-react-native.svg",
  nextjs: "/icons/icons8-nextjs.svg",
  nodejs: "/icons/icons8-nodejs.svg",
  expressjs: "/icons/icons8-express-js.svg",
  npm: "/icons/icons8-npm.svg",
  firebase: "/icons/icons8-firebase.svg",
  mongodb: "/icons/icons8-mongodb.svg",
  mysql: "/icons/icons8-mysql.svg",
  git: "/icons/icons8-git.svg",
  github: "/icons/icons8-github.svg",
  figma: "/icons/icons8-figma.svg",
  vite: "/icons/icons8-vite.svg",
  linux: "/icons/linux.svg",
};

export const projectData = [
  { number: 1, name: "WhatsApp Bot", github: "https://github.com/adi-pr/whatsapp-bot.git" },
  { number: 2, name: "Car Showcase Website", github: "https://github.com/adi-pr/car-showcase-website.git" },
  { number: 3, name: "Library Manager (Built with Python Tkinter)", github: "https://github.com/adi-pr/Library-Manager.git" },
  { number: 4, name: "CV Application", github: "https://github.com/adi-pr/cv-application.git" },
];
